packages:
  - apps/*
  - packages/*

catalog:
  '@commitlint/cli': ^21.0.2
  '@commitlint/config-conventional': ^21.0.2
  '@eslint/js': ^10.0.1
  '@tanstack/vue-query': ^5.101.0
  '@vitejs/plugin-vue': ^6.0.7
  element-plus: ^2.14.2
  eslint: ^10.5.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-vue: ^10.9.2
  globals: ^17.6.0
  husky: ^9.1.7
  lint-staged: ^17.0.7
  msw: ^2.14.6
  orval: ^8.17.0
  pinia: ^3.0.4
  prettier: ^3.8.4
  reka-ui: ^2.9.10
  sass: ^1.101.0
  style-dictionary: ^5.4.4
  turbo: ^2.9.18
  typescript: ^6.0.3
  typescript-eslint: ^8.61.1
  vite: ^8.0.16
  vue: ^3.5.38
  vue-router: ^5.1.0
  vue-tsc: ^3.3.5

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  msw: true
  vue-demi: true
