export { PharmApiError, normalizeApiError } from './errors'
export { apiClient, createApiClient } from './http/client'
export { getProducts } from './domain/product.api'
export type { ApiError, ApiFieldError } from './errors'
export type { ApiRequestInit, ApiClientOptions } from './http/client'
export type { ProductSummary } from './domain/product.api'
export type { ApiSuccess, PageData } from './types'
